### ISSUE TITLE
因为项目在本地git仓库，服务器需要用git部署，部署后无法打开

### ISSUE THREAD

**Issue by gongchao** [medz/phpwind#101]
Uncaught error with message 'Not exist view template file or Incorrect file path '[viewer.WindLayout.parser] layout file /opt/site/forum/data/compile/template/default/common/layout_error.tpl''

The server encountered an internal error and failed to process your request. Please try again later. If this error is temporary, reloading the page might resolve the problem. 
If you are able to contact the administrator report this error message.(http://www.windframework.com/)

应该是缓存问题，哪里关闭全站缓存呢？或者如何解决这种问题？

**Comment by medz** [comment]
qq已经解答～

**Comment by friendly63** [comment]
部署linux 需要把文件夹 子文件夾赋权限
