### ISSUE TITLE
pw9里，所有管理员都可以看到后台-内容-私信，建议修改

### ISSUE THREAD

**Issue by Syntacticlosure** [medz/phpwind#12]
修改为仅有创始人可以查看会员私信

**Comment by medz** [comment]
<img width="807" alt="qq20161106-1 2x" src="https://cloud.githubusercontent.com/assets/5564821/20038054/5c6fbe2c-a467-11e6-8048-bc1ed96c80e9.png">
后台有这个权限设置的
