### ISSUE TITLE
1.1 版本打开用户个人空间 BUG

### ISSUE THREAD

**Issue by SourcePowered** [medz/phpwind#257]
随意打开任意用户个人空间，会有类似以下提示：

> [db.WindSqlStatement.execute] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.pw_space' doesn't existSQL:SELECT * FROM pw_space WHERE uid = ?

这一定是个 BUG 啦。。。

**Comment by medz** [comment]
表缺失，已记录。

**Comment by medz** [comment]
已经修复。
