### ISSUE TITLE
PHP 5.6 版本无法正常安装。

### ISSUE THREAD

**Issue by SourcePowered** [medz/phpwind#258]
问题如图所示。
**经测试 7.0 以上版本没有此问题，应该是语法问题。**
![image](https://cloud.githubusercontent.com/assets/25248285/26689501/6cca5bc4-4728-11e7-952f-63aa98f8e439.png)

**Comment by medz** [comment]
目前因为刚好 zend group 发布了 php 7.2 所以今天开始fans 1.1 只从 php7 开始兼容三个版本：
- php 7.0
- php 7.1
- php 7.2
