### ISSUE TITLE
Not exist view template file or Incorrect file path

### ISSUE THREAD

**Issue by louisliaoxh1989** [medz/phpwind#267]
搜索时报错
Not exist view template file or Incorrect file path '[viewer.resolver.WindViewerResolver.compile] /var/www/html/phpwind1/phpwind9/template/search/search_run.htm'

**Comment by medz** [comment]
不在老版本支持搜索

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年6月26日，19:50，lxh <notifications@github.com<mailto:notifications@github.com>> 写道：


搜索时报错
Not exist view template file or Incorrect file path '[viewer.resolver.WindViewerResolver.compile] /var/www/html/phpwind1/phpwind9/template/search/search_run.htm'

**Comment by louisliaoxh1989** [comment]
my system version is 
phpwind Fans 1.1.0

**Comment by medz** [comment]
我知道的，搜索功能会在 API 中提供，正式版没有 /old 路由的～
