### ISSUE TITLE
操作 php wind install 时出现错误

### ISSUE THREAD

**Issue by Sefank** [medz/phpwind#269]
安装v1.1.0-alpha.1，在操作`php wind install`时出现错误。

错误代码：

>   [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `pw_design_portal` add index `pw_design_portal_domain_index`(`domain`))
  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

环境：

- Apache 2.4
- MySQL 5.6.35
- PHP 7.1

**Comment by medz** [comment]
sorry，该命令已经废弃。

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年8月2日，13:39，Sefank <notifications@github.com<mailto:notifications@github.com>> 写道：


安装v1.1.0-alpha.1，在操作php wind install时出现错误。

错误代码：

[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table pw_design_portal add index pw_design_portal_domain_index(domain))
[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

环境：

  *   Apache 2.4
  *   MySQL 5.6.35
  *   PHP 7.1
