### ISSUE TITLE
安装失败 进行到old/install.php?a=database

### ISSUE THREAD

**Issue by mai1015** [medz/phpwind#272]
http://localhost:8080/old/install.php?a=database 出现500错误。
php没有报错但是nginx报错
2017/09/05 06:28:14 [error] 6838#0: *6 FastCGI sent in stderr: "Unable to open primary script: /usr/share/nginx/html/public/old/install.php (No such file or directory)" while reading response header from upstream, client: 10.0.2.2, server: localhost, request: "GET /old/install.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"

**Comment by medz** [comment]
额～这是你的问题咯～

**Comment by mai1015** [comment]
但是其他都正常啊，就到这一步就错了。

**Comment by medz** [comment]
请等待十一后发布的正式版


Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年9月28日，19:44，mai1015 <notifications@github.com<mailto:notifications@github.com>> 写道：


但是其他都正常啊，就到这一步就错了。
