### ISSUE TITLE
支持国际化吗

### ISSUE THREAD

**Issue by yujianFresh** [medz/phpwind#273]
请问这个版本的phpwind支持国际化吗，比如同时能支持中英文，目前装的9.0只能采用google翻译才能显示出英文。

**Comment by medz** [comment]
fans 1.1 会逐步支持国际化。

**Comment by yujianFresh** [comment]
大概什么时候会支持呢，如果短时间内需要这个功能，是不是整个论坛都需要自己写，才能够搞定。

**Comment by medz** [comment]
国庆过后发布第一个版本就会支持一部分～年底争取全部支持。

**Comment by yujianFresh** [comment]
请问这一部分包含论坛首页，以及发帖那块的中英文吗，如果是这样的话，那对我们而言就够了，如果不支持，我们只能再寻求其他的论坛项目了。。

**Comment by medz** [comment]
由用户或者站长选择语言。1.1 会支持中文和英文


Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年9月19日，12:08，yujianFresh <notifications@github.com<mailto:notifications@github.com>> 写道：


请问这一部分包含论坛首页，以及发帖那块的中英文吗，如果是这样的话，那对我们而言就够了，如果不支持，我们只能再寻求其他的论坛项目了。。

**Comment by yujianFresh** [comment]
对了，你们能不能在国庆后的那版中，用户设置那边可以选择语言，中文or英文，这样的话就支持国际化了，我看到很多其他的论坛都是这样做的，目前我们已经采用phpwind上线论坛了，所以如果再用其他的开源论坛搭建一个，太耗时耗力了，你们那边需要什么帮助，我们这边尽力支持。希望十一那版能带上这个功能。。
