### ISSUE TITLE
请问这里还能讨论FANS 1.0.10版本吗？

### ISSUE THREAD

**Issue by wzzjhc** [medz/phpwind#279]
```
请问这里还能讨论FANS 1.0.10版本吗？
如果可以讨论，我想咨询一个问题。
后台-->用户管理-->编辑某个用户的时候。也就是文件template/u/admin/manage_edit.htm。
我在基本资料的真实姓名前面加了一个LOVE
 ```
 
		<tr>
			<th>LOVE</th>
			<td><input name="love" type="text" class="input length_5" value="{$info['love']}"></td>
		</tr>
		<tr>
			<th>真实姓名</th>
			<td><input name="realname" type="text" class="input input_hd length_5" value="{$info['realname']}"></td>
		</tr>
```

    我知道改htm是没用的，还要去修改控制。但是在这个htm里面看不出是受那个文件控制的，因为真实姓名这一栏里的name属性是realname，所以通过检索realname这个关键词，我检索了整个phpwind文件夹，最后凭感觉，应该是在/src/applications/u/admin/ManageController.php，因为两个文件的路径里都有一个u。
    最后找到里面确实有个控制realname的函数，于是我模仿它写了一个love，区分了大小写。但是我知道这肯定不够，$dm跟seLove又是被哪个文件控制的呢？


```
        //基本资料
	 $dm->setLove($this->getInput('love', 'post'));
        $dm->setRealname($this->getInput('realname', 'post'));
```
最后发现但是不确定，很可能$dm来自这2个命令。
```
    Wind::import('SRC:service.user.dm.PwUserInfoDm');
            $dm = new PwUserInfoDm();
```
然后找到/src/service/user/dm/PwUserInfoDm.php
在里面找到这样子的一个代码
```
    /**
     * 设置真实姓名.
     *
     * @param string $realname
     *
     * @return PwUserInfoDm
     */
    public function setRealname($realname)
    {
        $this->getDm()->setRealname($realname);
        $this->_data['realname'] = $realname;

        return $this;
    }
```
于是我模仿它写了一个love
```
    /**
     * 设置love.
     *
     * @param string $love
     *
     * @return PwUserInfoDm
     */
    public function setLove($love)
    {
        $this->getDm()->setLove($love);
        $this->_data['love'] = $love;

        return $this;
    }
```
我以为这样子就好了，但是运行的时候，后台就报错了。
我觉得我应该需要帮助
```

**Comment by medz** [comment]
你代码没有问题 问题在 你数据库数据表没有love字段 添加上即可

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年3月4日，15:31，wzzjhc <notifications@github.com<mailto:notifications@github.com>> 写道：


请问这里还能讨论FANS 1.0.10版本吗？
如果可以讨论，我想咨询一个问题。
后台-->用户管理-->编辑某个用户的时候。也就是文件template/u/admin/manage_edit.htm。
我在基本资料的真实姓名前面加了一个LOVE


        <tr>
                <th>LOVE</th>
                <td><input name="love" type="text" class="input length_5" value="{$info['love']}"></td>
        </tr>
        <tr>
                <th>真实姓名</th>
                <td><input name="realname" type="text" class="input input_hd length_5" value="{$info['realname']}"></td>
        </tr>



    我知道改htm是没用的，还要去修改控制。但是在这个htm里面看不出是受那个文件控制的，因为真实姓名这一栏里的name属性是realname，所以通过检索realname这个关键词，我检索了整个phpwind文件夹，最后凭感觉，应该是在/src/applications/u/admin/ManageController.php，因为两个文件的路径里都有一个u。
    最后找到里面确实有个控制realname的函数，于是我模仿它写了一个love，区分了大小写。但是我知道这肯定不够，$dm跟seLove又是被哪个文件控制的呢？




    //基本资料
 $dm->setLove($this->getInput('love', 'post'));
    $dm->setRealname($this->getInput('realname', 'post'));


最后发现但是不确定，很可能$dm来自这2个命令。


Wind::import('SRC:service.user.dm.PwUserInfoDm');
        $dm = new PwUserInfoDm();


然后找到/src/service/user/dm/PwUserInfoDm.php
在里面找到这样子的一个代码


/**
 * 设置真实姓名.
 *
 * @param string $realname
 *
 * @return PwUserInfoDm
 */
public function setRealname($realname)
{
    $this->getDm()->setRealname($realname);
    $this->_data['realname'] = $realname;

    return $this;
}


于是我模仿它写了一个love


/**
 * 设置love.
 *
 * @param string $love
 *
 * @return PwUserInfoDm
 */
public function setLove($love)
{
    $this->getDm()->setLove($love);
    $this->_data['love'] = $love;

    return $this;
}


我以为这样子就好了，但是运行的时候，后台就报错了。
我觉得我应该需要帮助

**Comment by wzzjhc** [comment]
我是在数据库表  _user 下建的一个love字段。但是我在后台提交的编辑表单的时候会提示：internal server error，是我字段建错表了吗？

**Comment by medz** [comment]
你的分支在啥地方？ 我可以帮你写一下这个


Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年3月4日，16:33，wzzjhc <notifications@github.com<mailto:notifications@github.com>> 写道：


我是在数据库表 _user 下建的一个love字段。但是我在后台提交的编辑表单的时候会提示：internal server error，是我字段建错表了吗？

**Comment by wzzjhc** [comment]
sorry  我不理解你讲的分支是什么含义。

**Comment by wzzjhc** [comment]
算了，我已经用暴力代码解决了。
我只是希望能通过phpwind系统自身的函数来解决问题。
只能说我自己功力尚浅。
