### ISSUE TITLE
PHP7环境开启伪静态情况下出错

### ISSUE THREAD

**Issue by jia-dai** [medz/phpwind#34]
涉及文件：src/library/route/PwRoute.php
242行：
`if ($route[$k] === $router->$methods[$k]() && $flag === $flags[$k]) {`
改为：
```
	    $method = $methods[$k];
            if ($route[$k] === $router->$method() && $flag === $flags[$k]) {
```
以上问题仅在PHP7环境出现。供参考。

**Comment by medz** [comment]
好的～感谢～
