### ISSUE TITLE
composer中Wekit引入大小写问题

### ISSUE THREAD

**Issue by jia-dai** [medz/phpwind#37]
autoload文件中，引入类的文件名相关语句为：
`'Wekit' => $baseDir . '/src/Wekit.php',`
实际文件为`/src/wekit.php`，w为小写，Linux系统会导致引入类文件失败。

**Comment by medz** [comment]
fans版本中是驼峰式的，你应该是覆盖升级吧？有些平台不区分大小写，所以覆盖了，文件名还是小写，你要自己重命名为正确的大些文件。

**Comment by jia-dai** [comment]
嗯，Windows系统覆盖时不改大小写，还保留原来的文件名。上传到服务器后就出现了这个问题，如果是都在一个环境操作的话应该不存在这个问题。
