### ISSUE TITLE
支持HTTPS

### ISSUE THREAD

**Issue by acgmoe** [medz/phpwind#55]
是否可以支持HTTPS

**Comment by medz** [comment]
年后版本改改后会支持～

**Comment by devmings** [comment]
conf/publish.php中对PUBLIC_URL赋值https://xxxx.com   基本上没发生啥问题

**Comment by medz** [comment]
目前，phpwind Fans版本支持https，启用https如果要保证windid的API请求成功～需要对fsockopen支持openssl，是的"ssl://host"能打开套字节～
