### ISSUE TITLE
win10 下 phpwind 部分JS事件失灵

### ISSUE THREAD

**Issue by onoff888** [medz/phpwind#63]
应该是和系统有关系，我在win7下功能都是正常的。win10下"模块管理"和"个人空间设置"的按键都无法使用。测试浏览器有"360急速浏览器"和"chrome"，如果把360切换IE11可以正常访问。
希望下个版本修复一下win10浏览器的兼容性。

**Comment by medz** [comment]
并不会修复，这个会在后续版本中移除。

Seven Du <lovevipdsw@outlook.com<mailto:lovevipdsw@outlook.com>>

在 2016年11月27日，23:12，onoff888 <notifications@github.com<mailto:notifications@github.com>> 写道：


应该是和系统有关系，我在win7下功能都是正常的。win10下"模块管理"和"个人空间设置"的按键都无法使用。测试浏览器有"360急速浏览器"和"chrome"，如果把360切换IE11可以正常访问。
希望下个版本修复一下win10浏览器的兼容性。

―
