### ISSUE TITLE
WindidUtility.php：怪异的continue。PHP7测试无法登录。

### ISSUE THREAD

**Issue by jia-dai** [medz/phpwind#67]
src/windid/service/base/WindidUtility.php
第109行。怪异的continue。PHP7测试无法登录。建议考虑注释掉。

```php
            if (!isset($exts[$imageInfo[2]])) {
                //continue;
            }
```

**Comment by medz** [comment]
并没有无法登陆，你应该打印错误信息～而不是删代码～

**Comment by jia-dai** [comment]
[2016-12-01 07:13:01] ERROR! Message:  Class 'WindidUtility' not found
I:\PHPWeb\pw9\src\windid\api\local\WindidUserApi.php:28
#15  I:\PHPWeb\pw9\src\windid\api\local\WindidUserApi.php (28) login("admin","xxxxxxx",2,false,null,null)
#14  I:\PHPWeb\pw9\src\service\user\srv\PwTryPwdBp.php (80) login("admin","xxxxxxx",2,false,null,null)
#13  I:\PHPWeb\pw9\src\service\user\srv\PwLoginService.php (51) auth("admin","xxxxxxx","::1",false,null,null)
#12  I:\PHPWeb\pw9\src\applications\u\controller\LoginController.php (272) login("admin","xxxxxxx","::1",null,null)
#11  I:\PHPWeb\pw9\vendor\medz\windframework\wind\web\WindSimpleController.php (49) dorunAction()
#10  I:\PHPWeb\pw9\vendor\medz\windframework\wind\filter\WindHandlerInterceptorChain.php (68) doAction(WindRouter)
#09  I:\PHPWeb\pw9\vendor\medz\windframework\wind\filter\WindHandlerInterceptor.php (68) handle(WindRouter)
#08  I:\PHPWeb\pw9\vendor\medz\windframework\wind\filter\WindHandlerInterceptor.php (66) handle(WindRouter)
#07  I:\PHPWeb\pw9\vendor\medz\windframework\wind\filter\WindHandlerInterceptor.php (66) handle(WindRouter)
#06  I:\PHPWeb\pw9\vendor\medz\windframework\wind\filter\proxy\WindClassProxy.php (107) handle(WindRouter)
#05  I:\PHPWeb\pw9\vendor\medz\windframework\wind\base\AbstractWindApplication.php (94) __call("doAction",array(
	'0' => NULL,
))
#04  I:\PHPWeb\pw9\vendor\medz\windframework\wind\base\AbstractWindFrontController.php (217) run(WindRouter)
#03  I:\PHPWeb\pw9\vendor\medz\windframework\wind\web\WindWebFrontController.php (23) run()
#02  I:\PHPWeb\pw9\src\Wekit.php (41) run()
#01  I:\PHPWeb\pw9\index.php (10) run("phpwind")

**Comment by jia-dai** [comment]
整个代码没看到循环，不大理解这里continue的作用。

**Comment by medz** [comment]
WindidUtility找不到这个类～

**Comment by medz** [comment]
可能是加载问题～什么情况下出现的？请问下～

**Comment by medz** [comment]
修复了~
