### ISSUE TITLE
使用 clipboard.min.js

### ISSUE THREAD

**Issue by kinosang** [medz/phpwind#84]
zeroClipboard 依赖 Flash 插件，推荐使用 clipboard.min.js 取代。

**Comment by medz** [comment]
你好～这个因为pw内置主体不会增加功能～只修复bug～1.1版本会提供其他模式，比如单页应用，这个问题可以留着，等第三方来提交对应代码吧～

**Comment by kinosang** [comment]
个人认为这不是增加feature，而是修复bug。

Flash已经被大部分浏览器抛弃，所以PHPWind的复制功能将无法在主流平台上使用。

**Comment by medz** [comment]
这个只能算功能增强，增加兼容性，并非bug～

**Comment by likeclub** [comment]
都不兼容当今主流浏览器了还不算Bug?请问什么才是Bug?上次和一个2B汉化程序的家伙理论，大陆使用登录比登入频繁且主流，这个小2B说登入才是正宗的登录。任何和广大用户作对的2B都要被骂？楼主明白我意思不？你不顾用户体验坚持这个不是BUG，我觉得你没能力去维护这个项目，交给更加合适的人吧。用淘汰的技术来做web，请问你问过市场还是问过用户？你不听用户意见执拗什么玩意儿！

**Comment by likeclub** [comment]
再换个观念来说，既然你认为这个不是bug。你干嘛修复ssl问题，你不是没事找事吗？你是偷懒还是没本事做，你可能有万千委屈，我也认同你为开源做出的努力，但是你这副不听用户意见的态度还强词夺理我看不下去也觉得你毫无道理和逻辑。你如果偷懒麻烦直接说，你没能力修复也直接说，别忽悠站长说这个不是BUG!人家他妈的用户都上传不了附件了还不是BUG?你够狠够拽，妈了比和那个汉化的小二逼同出一辙物以类聚。 @medz @kinosang

**Comment by kinosang** [comment]
@likeclub 虽然我也认为这个问题亟待修复，但是您的言行实在不当。送您一句话，fork to create your own branch.

**Comment by likeclub** [comment]
@kinosang 和你说个事情，那个2B汉化小伙子过了几个月默默的把登入换成了登录。当初是何其嘴犟何其有理，态度决定一切，耐心虚心去倾听用户意见。我看不惯我就会去骂，我骂的是他的态度而不是他本人。

**Comment by likeclub** [comment]
@kinosang 这个只能算功能增强，增加兼容性，并非bug～，从一个码农嘴里说出这等low的言语，我看不出你的水平高大哪里去。PW是一个没人管理的项目，官方不作为了，所以劝你既然自己撸起袖子干起来就给我干好，否则这等吃力不讨好的事情还是敬而远之，别给我蹦出来一个这个不是Bug的低等回答暴露出无能，我对你人心存感激，但是你的态度我不敢苟同，你赞不赞同我都会鄙视你的这副态度！

**Comment by likeclub** [comment]
@medz 如果你说你不修复这个bug我毫无意见，但是你掩耳盗铃糊弄大家就是你的问题了。老外的开源我接触过很多程序员，头一次遇到你这样明明是自己偷懒或者不会修复说成这不是bug。你可以说我找人去研究，但是你一个码农起码的职业素养和精神在哪里，到了任何单位和你的老板都说这不是Bug。你可以唾弃这个老板，但是说好前麻烦严谨一点。任何与当代主流不符合的东西都是bug，别和我说你还兼容上个世纪的浏览器。flash淘汰了哥们，你不知道flash也频繁爆出漏洞啊！

**Comment by medz** [comment]
@likeclub 并不是我不修复～你住看开发计划～这部分在年中会被删除，或者保留不使用，因为phpwind fans要做前后端分离～这部分属于前端问题～替换一个按钮～无非就是加个dom的事情，这个问题确实只能定义成功能增强或者兼容性增强～而这部分在前后端分离后在spa中是不会存在的～我前面也说了，这个修改交给其他人提交代码～我的精力在整个phpwind的维护上～ 其次，我不想证明我的能力～

**Comment by medz** [comment]
我也说了～这个issue保留～等待其他人提交commit，这个问题是个前端，花一两个小时就能测试解决ok的～

**Comment by medz** [comment]
@kinosang 已经使用 [clipboard.js](https://github.com/zenorocha/clipboard.js) 替代 pw原有的 falsh 复制功能～感谢提交 issue

**Comment by medz** [comment]
@kinosang zeroClipboard 暂时不会删除～因为部分插件如果有复制功能～已久在使用改复制库。 clipboard.js 缺陷是对比较旧的浏览器兼容不好。

**Comment by medz** [comment]
@likeclub 如果你觉得falsh不爽～楼主的那句话 “fork to create your own branch.” pw开发的时间在2011年-2012年，pw才选择falsh的～pw程序有很多地方已经深度使用flash功能实现～比如附件上传～要改这部分本身需要花费比较多的精力～个人精力有限～并且，还有两三个月就会废弃这部分代码～你来告诉我，花费精力修改的意义何在？
