### ISSUE TITLE
火狐谷歌浏览器代码高亮问题

### ISSUE THREAD

**Issue by coolboy1** [medz/phpwind#85]
代码高亮：shCore.js 有报错

**Comment by medz** [comment]
请提供截图，或者复制console错误信息给我～谢谢咯～

**Comment by coolboy1** [comment]
![qq 20170121212342](https://cloud.githubusercontent.com/assets/17312283/22614332/9bdbf482-eabb-11e6-8caf-3a8804234ebd.jpg)

**Comment by medz** [comment]
你好～这个问题无法修复～因为匹配规则的问题～使用的代码高亮库属于第三发～目前会删除该库～不在提高插入代码功能～由前后端分离后，统一markdown实现～感谢关注。
