### ISSUE TITLE
功能改进

### ISSUE THREAD

**Issue by shewoqishui** [medz/phpwind#86]
希望加入wap模板，哪怕是简洁版的也行。

**Comment by medz** [comment]
会有全新前端后分离开发技术～届时会开发默认的手机但也应用～废弃pw9的模板机制。转而提供一整套完整的API，由前端开发中不需要关心逻辑的前提下开发单页应用。

在 2017年2月5日，11:36，shewoqishui <notifications@github.com<mailto:notifications@github.com>> 写道：


希望加入wap模板，哪怕是简洁版的也行。

**Comment by shewoqishui** [comment]
谢谢，你很棒！

**Comment by medz** [comment]
这个已经确定会开发分离～issue关闭～
