### ISSUE TITLE
建议增加后台清理站内消息功能

### ISSUE THREAD

**Issue by lkddi** [medz/phpwind#90]
论坛 站内通知及站内消息，如果运行时间较长，会占用部分数据库资源。
应该增加清理功能

1、后台 手动清理指定类型的 比如：已读消息、站内通知  可以选择消息时间截止日期。
2、定时自动清理指定类型的消息。

望考虑增加。

**Comment by medz** [comment]
这个不会加，程序的目的是收纳数据，这类数据属于用户隐私数据，不管逻辑如何，从法律角度，这个数据属于用户的，不属于网站，网站无权删除。而且网站还要承担保存义务。

Seven Du <lovevipdsw@outlook.com<mailto:lovevipdsw@outlook.com>>

在 2017年2月8日，18:06，lkddi <notifications@github.com<mailto:notifications@github.com>> 写道：


论坛 站内通知及站内消息，如果运行时间较长，会占用部分数据库资源。
应该增加清理功能

1、后台 手动清理指定类型的 比如：已读消息、站内通知 可以选择消息时间截止日期。
2、定时自动清理指定类型的消息。

望考虑增加。

―
