### ISSUE TITLE
后台功能”全局-积分设置-积分转换“以及”积分充值“错误

### ISSUE THREAD

**Issue by Sefank** [medz/phpwind#99]
这里给出”全局-积分设置-积分转换“的错误信息：
> Uncaught error with message 'E_WARNING: Invalid argument supplied for foreach()'
> D:\phpStudy\WWW\data\compile\template\credit\admin\credit_exchange.tpl: 57
> 
> 52: &lt;td&gt;启用&lt;/td&gt;
> 53: &lt;td&gt;操作&lt;/td&gt;
> 54: &lt;/tr&gt;
> 55: &lt;/thead&gt;
> 56: &lt;tbody&gt;
> 57: &lt;?php foreach ($exchange as $key =&gt; $value) { ?&gt;
> 58: &lt;tr&gt;
> 59: &lt;td&gt;&lt;?php echo htmlspecialchars($value['value1'], ENT_QUOTES, 'UTF-8');?&gt;个&lt;?php echo htmlspecialchars($creditBo-&gt;cType[$value['credit1']], ENT_QUOTES, 'UTF-8');?&gt;&lt;/td&gt;
> 60: &lt;td&gt;兑换&lt;/td&gt;
> 61: &lt;td&gt;&lt;?php echo htmlspecialchars($value['value2'], ENT_QUOTES, 'UTF-8');?&gt;个&lt;?php echo htmlspecialchars($creditBo-&gt;cType[$value['credit2']], ENT_QUOTES, 'UTF-8');?&gt;&lt;/td&gt;
> __Stack:
> 
> #12 D:\phpStudy\WWW\vendor\medz\windframework\wind\base\AbstractWindFrontController.php (262)
> #11 D:\phpStudy\WWW\data\compile\template\credit\admin\credit_exchange.tpl (57) _errorHandle(2,"Invalid argument supplied for foreach()","D:\phpStudy\WWW\data\compile\template\credit\admin\credit_exchan…",57,array( '__tpl' => 'D:\\phpStudy\\WWW\\data\\compile/template/credit/admin/credit_exchange.tpl', '__vars' => array( 'loginUser' => NULL, 'creditBo' => NULL, 'exchange' => '', 'currentTabs' => array( 'run' => '', 'strategy' => '', 'recharge' => '', 'exchange' => 'current', 'transfer' => '', 'log' => '', ), ), '__viewer' => NULL, 'loginUser' => NULL, 'creditBo' => NULL, 'exchange' => '', 'currentTabs' => array( 'run' => '', 'strategy' => '', 'recharge' => '', 'exchange' => 'current', 'transfer' => '', 'log' => '', ), ))
> #10 D:\phpStudy\WWW\vendor\medz\windframework\wind\viewer\IWindViewerResolver.php (57) include("D:\phpStudy\WWW\data\compile\template\credit\admin\credit_exchan…")
> #09 D:\phpStudy\WWW\vendor\medz\windframework\wind\viewer\resolver\WindViewerResolver.php (43) render("D:\phpStudy\WWW\data\compile/template/credit/admin/credit_exchan…",array( 'loginUser' => NULL, 'creditBo' => NULL, 'exchange' => '', 'currentTabs' => array( 'run' => '', 'strategy' => '', 'recharge' => '', 'exchange' => 'current', 'transfer' => '', 'log' => '', ), ),WindViewerResolver)
> #08 D:\phpStudy\WWW\vendor\medz\windframework\wind\viewer\WindView.php (152) windFetch()
> #07 D:\phpStudy\WWW\vendor\medz\windframework\wind\web\WindDispatcher.php (44) render(false)
> #06 D:\phpStudy\WWW\vendor\medz\windframework\wind\web\WindWebApplication.php (32) dispatch(WindForward,WindRouter,false)
> #05 D:\phpStudy\WWW\vendor\medz\windframework\wind\base\AbstractWindApplication.php (95) doDispatch(WindForward)
> #04 D:\phpStudy\WWW\vendor\medz\windframework\wind\base\AbstractWindFrontController.php (217) run(WindRouter)
> #03 D:\phpStudy\WWW\vendor\medz\windframework\wind\web\WindWebFrontController.php (23) run()
> #02 D:\phpStudy\WWW\src\Wekit.php (41) run()
> #01 D:\phpStudy\WWW\admin.php (11) run("pwadmin",array( 'router' => array( 'config' => array( 'module' => array( 'default-value' => 'default', ), 'routes' => array( 'admin' => array( 'class' => 'LIB:route.PwAdminRoute', 'default' => true, ), ), ), ), ))

**Comment by medz** [comment]
我排查下


Seven Du <lovevipdsw@outlook.com<mailto:lovevipdsw@outlook.com>>

在 2017年3月5日，16:29，Sefank <notifications@github.com<mailto:notifications@github.com>> 写道：


这里给出”全局-积分设置-积分转换“的错误信息：

Uncaught error with message 'E_WARNING: Invalid argument supplied for foreach()'
D:\phpStudy\WWW\data\compile\template\credit\admin\credit_exchange.tpl: 57

52: <td>启用</td>
53: <td>操作</td>
54: </tr>
55: </thead>
56: <tbody>
57: <?php foreach ($exchange as $key => $value) { ?>
58: <tr>
59: <td><?php echo htmlspecialchars($value['value1'], ENT_QUOTES, 'UTF-8');?>个<?php echo htmlspecialchars($creditBo->cType[$value['credit1']], ENT_QUOTES, 'UTF-8');?></td>
60: <td>兑换</td>
61: <td><?php echo htmlspecialchars($value['value2'], ENT_QUOTES, 'UTF-8');?>个<?php echo htmlspecialchars($creditBo->cType[$value['credit2']], ENT_QUOTES, 'UTF-8');?></td>
__Stack:

#12<https://github.com/medz/phpwind/issues/12> D:\phpStudy\WWW\vendor\medz\windframework\wind\base\AbstractWindFrontController.php (262)
#11<https://github.com/medz/phpwind/issues/11> D:\phpStudy\WWW\data\compile\template\credit\admin\credit_exchange.tpl (57) _errorHandle(2,"Invalid argument supplied for foreach()","D:\phpStudy\WWW\data\compile\template\credit\admin\credit_exchan…",57,array( '__tpl' => 'D:\phpStudy\WWW\data\compile/template/credit/admin/credit_exchange.tpl', '__vars' => array( 'loginUser' => NULL, 'creditBo' => NULL, 'exchange' => '', 'currentTabs' => array( 'run' => '', 'strategy' => '', 'recharge' => '', 'exchange' => 'current', 'transfer' => '', 'log' => '', ), ), '__viewer' => NULL, 'loginUser' => NULL, 'creditBo' => NULL, 'exchange' => '', 'currentTabs' => array( 'run' => '', 'strategy' => '', 'recharge' => '', 'exchange' => 'current', 'transfer' => '', 'log' => '', ), ))
#10<https://github.com/medz/phpwind/pull/10> D:\phpStudy\WWW\vendor\medz\windframework\wind\viewer\IWindViewerResolver.php (57) include("D:\phpStudy\WWW\data\compile\template\credit\admin\credit_exchan…")
#9<https://github.com/medz/phpwind/pull/9> D:\phpStudy\WWW\vendor\medz\windframework\wind\viewer\resolver\WindViewerResolver.php (43) render("D:\phpStudy\WWW\data\compile/template/credit/admin/credit_exchan…",array( 'loginUser' => NULL, 'creditBo' => NULL, 'exchange' => '', 'currentTabs' => array( 'run' => '', 'strategy' => '', 'recharge' => '', 'exchange' => 'current', 'transfer' => '', 'log' => '', ), ),WindViewerResolver)
#8<https://github.com/medz/phpwind/pull/8> D:\phpStudy\WWW\vendor\medz\windframework\wind\viewer\WindView.php (152) windFetch()
#7<https://github.com/medz/phpwind/pull/7> D:\phpStudy\WWW\vendor\medz\windframework\wind\web\WindDispatcher.php (44) render(false)
#6<https://github.com/medz/phpwind/pull/6> D:\phpStudy\WWW\vendor\medz\windframework\wind\web\WindWebApplication.php (32) dispatch(WindForward,WindRouter,false)
#5<https://github.com/medz/phpwind/pull/5> D:\phpStudy\WWW\vendor\medz\windframework\wind\base\AbstractWindApplication.php (95) doDispatch(WindForward)
#4<https://github.com/medz/phpwind/pull/4> D:\phpStudy\WWW\vendor\medz\windframework\wind\base\AbstractWindFrontController.php (217) run(WindRouter)
#3<https://github.com/medz/phpwind/pull/3> D:\phpStudy\WWW\vendor\medz\windframework\wind\web\WindWebFrontController.php (23) run()
#2<https://github.com/medz/phpwind/pull/2> D:\phpStudy\WWW\src\Wekit.php (41) run()
#1<https://github.com/medz/phpwind/pull/1> D:\phpStudy\WWW\admin.php (11) run("pwadmin",array( 'router' => array( 'config' => array( 'module' => array( 'default-value' => 'default', ), 'routes' => array( 'admin' => array( 'class' => 'LIB:route.PwAdminRoute', 'default' => true, ), ), ), ), ))

**Comment by medz** [comment]
@Sefank 已经修复～

**Comment by Sefank** [comment]
Good job~

**Comment by medz** [comment]
@Sefank Thanks.
